version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:8-jdk
        user: root
      - image: mongo:latest
    working_directory: /go/src/duty-designator
    steps:
      - checkout
      - run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - run: echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
      - run: apt-get update
      - run: |
          apt-get install -y dbus-x11 google-chrome-stable libgtk2.0-0 \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          xvfb \
          gcc \
          libxml2-utils
      - run: rm -rf /var/lib/apt/lists/*
      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "./e2e/package.json" }}
      - restore_cache:
          keys:
            - cache-6-{{ arch }}-{{ .Branch }}-{{ checksum "./server/gogradle.lock" }}
      - run: ./gradlew :server:goVendor nodeSetup yarnSetup
      - save_cache:
          key: cache-6-{{ arch }}-{{ .Branch }}-{{ checksum "./server/gogradle.lock" }}
          paths:
            - ./server/vendor
            - ./server/.gogradle
            - /root/.gradle
            - "~/.gradle"
      - run: ./gradlew check
      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "./e2e/package.json" }}
          paths:
            - ~/.cache
      - store_test_results:
          path: test-results
      - store_artifacts:
          destination: server
          path: /go/src/duty-designator/server/.gogradle/reports
      - store_artifacts:
          destination: e2e-videos
          path: e2e/cypress/videos
      - store_artifacts:
          destination: e2e-screenshots
          path: e2e/cypress/screenshots
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
  build-docker:
    docker:
      - image: docker:latest
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          docker_layer_caching:
      - run: |
          TAG=latest
          docker build -t riordanx0/duty-designator:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push riordanx0/duty-designator:$TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build-docker:
          requires:
            - build
          filters:
            branches:
              only: dockerizing
